# Generated by Django 5.1.1 on 2024-12-18 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_des', models.TextField()),
                ('task_type', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT')], max_length=100)),
                ('task_assign_to', models.ManyToManyField(related_name='Employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
